export const commentsAPI = [
  {
    id: 0,
    post: 0,
    name: "Julia Santos",
    avatar: 'http://picsum.photos/id/690/400',
    content: "Boa noite! Que legal! Adoro bolo de fubá, vou experimentar essa receita com certeza. Obrigado por compartilhar!",
    date: 1677109844,
    image: null,
    liked: false,
    feed: { likes: 134, views: 345 },
  },
  {
    id: 1,
    post: 0,
    name: "Gustavo da Silva",
    avatar: 'http://picsum.photos/id/193/400',
    content: " Uau, parece ótimo! Eu amo cozinhar e sempre estou procurando novas receitas para experimentar. Obrigado por compartilhar essa, com certeza vou testá-la em breve.",
    date: 1677129844,
    image: null,
    liked: false,
    feed: { likes: 78, views: 234 },
  },
  {
    id: 2,
    post: 0,
    name: "Marcelo Oliveira",
    avatar: 'http://picsum.photos/id/194/400',
    content: "Vou experimentar e depois te contar como ficou. Obrigado!",
    date: 1677130844,
    image: null,
    liked: false,
    feed: { likes: 23, views: 134 },
  },
  {
    id: 3,
    post: 2,
    name: "Matheus Oliveira Santos",
    avatar: 'http://picsum.photos/id/111/400',
    content: "Eu também assisti esse filme no cinema e concordo plenamente com sua opinião!",
    date: 1677119844,
    image: null,
    liked: false,
    feed: { likes: 94, views: 145 },
  },
  {
    id: 4,
    post: 4,
    name: "Henrique Costa Oliveira",
    avatar: 'http://picsum.photos/id/127/400',
    content: "Embora compreenda que tenha gostado, pessoalmente, achei que a jogabilidade e a variedade de personagens poderiam ter sido melhores. Acredito que mais conteúdo poderia ter melhorado a experiência.",
    date: 1677072034,
    image: null,
    liked: false,
    feed: { likes: 94, views: 145 },
  }
]